// Package main provides the entry point and core types for the Movie Review API.
// This file defines the data transfer objects (DTOs) and domain models used
// throughout the application for handling movie review data.
package main

import (
    "fmt"
    "time"
)

// CreateReviewRequest represents the expected JSON payload when creating a new review.
// This DTO is used to validate and parse incoming POST requests to the /review endpoint.
//
// Example JSON:
//
//	{
//	    "title": "Inception",
//	    "director": "Christopher Nolan",
//	    "releaseDate": "16 Jul 10 00:00 UTC",
//	    "rating": "9/10",
//	    "reviewNotes": "A mind-bending masterpiece"
//	}
type CreateReviewRequest struct {
    // Title is the name of the movie being reviewed.
    Title string `json:"title"`

    // Director is the name of the movie's director.
    Director string `json:"director"`

    // ReleaseDate is the movie's release date in RFC822 format (e.g., "02 Jan 06 15:04 MST").
    ReleaseDate string `json:"releaseDate"`

    // Rating is a string representation of the review score (e.g., "8/10", "4 stars").
    Rating string `json:"rating"`

    // ReviewNotes contains the reviewer's written comments about the movie.
    ReviewNotes string `json:"reviewNotes"`
}

// Review represents a complete movie review entity as stored in the database.
// This is the primary domain model used for CRUD operations and API responses.
//
// The ID field is auto-generated by the database (SERIAL PRIMARY KEY).
// The DateCreated field is automatically set when the review is created.
type Review struct {
    // ID is the unique identifier for the review, auto-generated by PostgreSQL.
    ID int `json:"id"`

    // Title is the name of the movie being reviewed.
    Title string `json:"title"`

    // Director is the name of the movie's director.
    Director string `json:"director"`

    // ReleaseDate is the formatted release date of the movie.
    ReleaseDate string `json:"releaseDate"`

    // Rating is a string representation of the review score.
    Rating string `json:"rating"`

    // ReviewNotes contains the reviewer's written comments about the movie.
    ReviewNotes string `json:"reviewNotes"`

    // DateCreated is the timestamp when this review was created, in RFC822 format.
    DateCreated string `json:"dateCreated"`
}

// NewReview creates a new Review instance with the provided details.
// It parses the releaseDate string (expected in RFC822 format) and sets
// the DateCreated field to the current time.
//
// Parameters:
//   - title: The name of the movie
//   - director: The director's name
//   - releaseDate: The release date in RFC822 format (e.g., "02 Jan 06 15:04 MST")
//   - rating: The review rating as a string
//   - reviewNotes: The reviewer's comments
//
// Returns:
//   - *Review: A pointer to the newly created Review instance
//
// Note: If the releaseDate cannot be parsed, the current time is used as a fallback
// and a warning is printed to stdout.
func NewReview(title string, director string, releaseDate string, rating string, reviewNotes string) *Review {
    dateTime, err := time.Parse(time.RFC822, releaseDate)
    if err != nil {
        fmt.Printf("Failed to Parse Date: Format 01 Jan 22 00:00 UTC You put: %s\n", releaseDate)
        // Use current time as fallback if parsing fails
        dateTime = time.Now()
    }
    
    // Format dates to a consistent 19-character string representation
    dateString := dateTime.Format(time.RFC822)[0:19]
    dateCreated := time.Now().Format(time.RFC822)[0:19]

    return &Review{
        Title:       title,
        Director:    director,
        ReleaseDate: dateString,
        Rating:      rating,
        ReviewNotes: reviewNotes,
        DateCreated: dateCreated,
    }
}